### ISSUE TITLE
Button renamed by ADT - Week2, Exercise 6, Step 2.4

### ISSUE THREAD

**Issue by AlexA-1809** [SAP-samples/abap-platform-rap-opensap#4]
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week2/unit6.md#step-2-create-the-service-binding

The button has been renamed from 'Activate' to 'Publish'

**Comment by CarineTD** [comment]
Hello Alex,

Thanks for the feedback.
Yes, this change - and others - comes with the most recent version of ADT plugin version (3.14).
We'll adjust the screenshots ASAP. 

As mentioned at the beginning of the exercises:  
*Please note that the ADT dialogs and views may change in the future due to software updates.*

Kind regards,
  Carine

**Comment by AlexA-1809** [comment]
see also 
https://github.com/SAP-samples/abap-platform-rap-opensap/blob/main/week4/unit5.md#step-2-create-service-binding
In step 2.4
'Press Activate (or in newer releases Publish)'
